#!/bin/bash

if [ "$#" -lt 3 ]; then
     echo "Usage: combine <EXP_DIR> <SUFFIX> <COMBINED_OUT_CSV>"
     exit 0
fi

SUFFIX=$2

rm -rf $1/csv
mkdir -p $1/csv
for i in $1/FINAL/*; do
    f=`basename $i`
    echo "*** $f ***"
    ln -s $i/$f.$SUFFIX $1/csv/
done

Rscript csv_combine.R $1/csv $3
