#!/bin/bash

mixtissues=(
  flower
  leaf
  root
  rosette
  seed
  seedling1wk
  seedling2wk
  shoot
  wholeplant
)

mixconditions=(
  stress-temperature
  stress-salt-drought
  stress-pathogen
  stress-other
  stress-light
  nutrients
  light
  hormone-ja-sa-ethylene
  hormone-aba-iaa-ga-br
  development
  chemical
)

if [ "$#" -lt 1 ]; then
     echo "Usage: mix_filterv1 ARRAY_CLASS_DIR [tissues/conditions]"
     echo "If second arg is tissues, ARRAY_CLASS_DIR should have as sub-dirs EXP_DIRs for ${mixtissues[@]} "
     echo "If second arg is conditions, ARRAY_CLASS_DIR should have as sub-dirs EXP_DIRs for ${mixconditions[@]} "
     echo "If second arg is not given, ARRAY_CLASS_DIR should have as sub-dirs EXP_DIRs for all conditions and tissues "
     exit 0
fi

classdir=$1
indtiss="true"
indcond="true"
if [ "$#" -gt 1 ]; then
	if [[ $2 == "tissues" ]]; then
		indcond="false"
	fi
	if [[ $2 == "conditions" ]]; then
		indtiss="false"
	fi
fi

echo "input args: $classdir $indtiss $indcond"

if [[ $indtiss == "true" ]]; then
  for tissue in "${mixtissues[@]}"; do
     echo "Running mixt for $tissue "
     echo Rscript mixt_filter.R ${classdir}/${tissue}/${tissue}-final-mas5-qn.csv ${classdir}/${tissue}/${tissue}-final-mas5-qn-mix-v1.csv 
     Rscript mixt_filter.R ${classdir}/${tissue}/${tissue}-final-mas5-qn.csv ${classdir}/${tissue}/${tissue}-final-mas5-qn-mix-v1.csv 
  done
fi
 
if [[ $indcond == "true" ]]; then
  for condition in "${mixconditions[@]}"; do
     echo "Running for $condition with threshold ${mixconditions[$condition]}"
     echo Rscript mixt_filter.R ${classdir}/${condition}/${condition}-final-mas5-qn.csv ${classdir}/${condition}/${condition}-final-mas5-qn-mix-v1.csv
     Rscript mixt_filter.R ${classdir}/${condition}/${condition}-final-mas5-qn.csv ${classdir}/${condition}/${condition}-final-mas5-qn-mix-v1.csv
  done
fi
