#!/bin/bash

if [ "$#" -lt 1 ]; then
     echo "Usage: mkexp <COMBINED_CSV_FILE> [<CSV2EXP_PATH> <PROBEID_TXT>]"
     exit 0
fi


csv2exp=./csv2exp
probe2id=/local/.DATA/sysbio/ATH1-Annotation/affy_ATH1_probe-id.txt
if [ "$#" -gt 2 ]; then
 if [ $2 != "-" ]; then
  csv2exp=$2
 fi
 if [ $3 != "-" ]; then
  probe2id=$3
 fi
fi

echo "input args: $1 $csv2exp $probe2id $4"

$csv2exp --match --map $probe2id $1

tmp=`mktemp`
out=`dirname $1`/`basename $1 .csv`

grep -v AFFX $out.exp > $tmp
./exp-clean-ht $tmp $out.exp > $out.log
rm $tmp
