#!/bin/bash
#
# Author: Sriram P C

if [ "$#" -lt 1 ]; then
     echo "Usage: ./gcplmstat <EXP_DIR>"
     exit 0
fi

for i in $1/CEL/*; do
    f=`basename $i`
    echo "*** $f ***"
    mkdir -p $1/QC/$f
    Rscript gcplmstat.R "$1/QC/$f/$f" $i
done

