#!/bin/bash

if [ "$#" -lt 3 ]; then
     echo "Usage: links <EXP_DIR> <TISSUE1> <TISSUE2> ..."
     exit 0
fi

mkdir -p $1/FINAL


for tx in ${*:2}; do
    tmpfy=`mktemp`
    echo $tmpfy
    cat ${tx}/QC/final-list.csv | cut -d, -f1 | uniq -d -c | grep -v " 2 " | sort -n |  cut -d'"' -f 2 | sort > $tmpfy
    for i in ${tx}/CEL/*; do
        d=`basename $i`
        list1=`grep $d $tmpfy`
        #echo $list1
        if [ -n "$list1" ]; then
            #echo $d
            mkdir -p $1/FINAL/$d
            for j in $i/*.[cC][eE][lL]* ; do
                f=$(basename "$j" | cut -d. -f1)
                #echo $f
                list=`grep -w "${f}" ${tx}/QC/final-accept.txt`
                if [ -n "$list" ]; then
                    echo ">$j<"
                    ln -s $j $1/FINAL/$d/
                fi
            done
        fi
    done
done
