#!/bin/bash
#
# Author: Jaroslaw Zola <jaroslaw.zola@gmail.com>

if [ "$#" -lt 1 ]; then
     echo "Usage: report <EXP_DIR>"
     exit 0
fi

if [ "$#" -lt 2 ]; then
 for i in $1/QC/*; do
    f=`basename $i`
    num=`cat $i/$f.sum | wc -l`
    if [ $num -gt 0 ]; then
	echo "reporting for $f: $num"
	Rscript plm.R $1/CEL/$f
	mv $1/CEL/$f/${f}_RLE_NUSE.pdf $i
    fi
 done
else
 echo $1 $2
 for i in $1/QC/$2*; do
    f=`basename $i`
    num=`cat $i/$f.sum | wc -l`
    if [ $num -gt 0 ]; then
	echo "reporting for $f: $num"
	Rscript plm.R $1/CEL/$f
	mv $1/CEL/$f/${f}_RLE_NUSE.pdf $i
    fi
 done
fi

