#!/bin/bash

if [ "$#" -lt 1 ]; then
     echo "Usage: stat <EXP_DIR>"
     echo "Lists the number of CEL files in each subdir of <EXP_DIR>/CEL/"
     exit 0
fi

wd=`pwd`
cd $1/CEL
for i in *; do
    cd $i
    num=`ls *.CEL *.cel *.cel.gz *.Cel *.Cel.gz 2> /dev/null | wc -l`
    echo -e "$i\t$num"
    cd ..
done
cd $wd
