#!/bin/bash
#
# Author: Jaroslaw Zola <jaroslaw.zola@gmail.com>

if [ "$#" -lt 1 ]; then
     echo "Usage: summary <EXP_DIR> [<PATTERN>]"
     exit 0
fi

totin=0
tot=0

if [ "$#" -lt 2 ]; then 
 for i in $1/QC/*; do
   if [ -d $i ]; then
    f=`basename $i`
    echo "*** $f : $i ***"
    Rscript summary.R $i
   fi
 done

 for i in $1/QC/*; do
   if [ -d $i ]; then
    f=`basename $i`
    nums=`cat $i/$f.sum | wc -l`
    tot=$(( $tot + $nums ))
    frac=$(( 2 * $nums ))
    ksf=$i/$f.ks
    if [ -f $ksf ]; then
     numk=`cat $i/$f.ks | wc -l`
    else
     numk=0
    fi
    totin=$(( $totin + $numk ))
    if [ $numk -lt $frac ]; then echo $f; fi
    echo "$nums out of $numk" > $i/$f.frac
   fi
 done
else
 for i in $1/QC/$2*; do
   if [ -d $i ]; then
     f=`basename $i`
     echo "*** $f : $i ***"
     Rscript summary.R $i
   fi
 done

 for i in $1/QC/$2*; do
   if [ -d $i ]; then
     f=`basename $i`
     nums=`cat $i/$f.sum | wc -l`
     tot=$(( $tot + $nums ))
     frac=$(( 2 * $nums ))
     ksf=$i/$f.ks
     if [ -f $ksf ]; then
      numk=`cat $i/$f.ks | wc -l`
     else
      numk=0
     fi
     totin=$(( $totin + $numk ))
     if [ $numk -lt $frac ]; then echo $f; fi
     echo "$nums out of $numk" > $i/$f.frac
   fi
 done
fi
echo Total "$tot/$totin" 
