#!/bin/bash
#
# Author: Sriram P C

if [ "$#" -lt 1 ]; then
     echo "Usage: summaryfull <EXP_DIR>"
     exit 0
fi

for i in $1/QC/*; do
    f=`basename $i`
    echo "*** $f : $i ***"
    Rscript summaryfull.R $i
done

#clear

totin=0
tot=0

for i in $1/QC/*; do
    f=`basename $i`
    nums=`cat $i/$f.fsum | wc -l`
    tot=$(( $tot + $nums ))
    frac=$(( 2 * $nums ))
    numk=`cat $i/$f.ks | wc -l`
    totin=$(( $totin + $numk ))
    if [ $numk -lt $frac ]; then echo $f; fi
    echo "$nums out of $numk" > $i/$f.frac
done

echo Total "$tot/$totin" 
