#!/usr/bin/perl

use strict;
use warnings;
use List::MoreUtils qw(uniq);

open(IN0, "< $ARGV[0]") or die "can't open input file\n";
open(IN1, "< $ARGV[1]") or die "can't open input file\n";

my %map0;
my %map1;

while (<IN0>) {
  chomp($_);
  my @line = split(' ', $_);
  $map0{$line[0]} = $line[1];
}

while (<IN1>) {
  chomp($_);
  my @line = split(' ', $_);
  $map1{$line[0]} = $line[1];
}

close(IN1);
close(IN0);

my $val0;
my $val1;

foreach my $key (keys %map0) {
    $val0 = $map0{$key};
    $val1 = $map1{$key};
#    $val0 = $val1 if (length($val0) < length($val1));
#    print "$key\t$val0\n";
    $val0 = '' if ($val0 =~ /no_match/);
    $val1 = '' if ($val1 =~ /no_match/);
    $val0 = 'no_match' if (length($val0) == 0 and length($val1) == 0);
    my @wx = sort(uniq(split(';', $val0), split(';', $val1)));
    my $jwx = join(';', uniq(@wx));
    print "$key\t$jwx\n"
}
