#!/bin/bash

shopt -s extglob

CPU=8
if [ "$#" -eq 1 ]; then
csv2exp=/local/zola/tinge-mi/bin/csv2exp
residuals=/local/zola/tinge-mi/bin/residuals
fi
if [ "$#" -eq 3 ]; then
csv2exp=$2
residuals=$3
fi

Rscript dirjustrma.R $1/CEL

for i in $1/CEL/*; do
    f=`basename $i`
    echo "*** $f ***"
    $csv2exp $i/$f.csv
    mpirun -np $CPU $residuals $i/$f.exp $i/$f.dres
    Rscript ks.R $i/$f.dres $i/$f.ks
    mkdir -p $1/QC/$f
    mv $i/$f.dres $1/QC/$f
    mv $i/$f.ks $1/QC/$f
    mv $i/$f.exp $1/QC/$f
    mv $i/$f.csv $1/QC/$f
done
