#!/bin/bash

if [ "$#" -lt 1 ]; then
     echo "Usage: report <EXP_DIR>"
     exit 0
fi

for i in $1/QC/*; do
    num=`basename $i`
    num=`cat $i/$f.sum | wc -l`
    if [ $num -gt 0 ]; then
	echo "reporting for $f: $num"
	Rscript plm.R $1/CEL/$f
	mv $1/CEL/$f/*.pdf $i
    fi
done

