#!/bin/bash
#
# Author: Jaroslaw Zola <jaroslaw.zola@gmail.com>

if [ "$#" -lt 1 ]; then
     echo "Usage: submean2 <EXP_DIR>"
     exit 0
fi

for i in $1/FINAL/*; do
    f = `basename $i`
    echo "*** $f ***"
    #cd $i
    #R_IN=$i.mas5.csv R_OUT=$i.log2.csv R --no-save < ../../submean2.R
    Rscript submean2.R $i/$f.mas5.csv $i/$f.m5.log2.csv
    #cd ..
done
